import type { GalleryItem } from '@/types/gallery'

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    images: ['/images/portfolio/portfolio-49.jpg'],
    piece: 'hyper-realism piece 1',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 1 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-50.jpg'],
    piece: 'hyper-realism piece 2',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 2 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-19.jpg'],
    piece: 'hyper-realism piece 3',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 3 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-51.jpg'],
    piece: 'hyper-realism piece 4',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 4 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-54.jpg'],
    piece: 'hyper-realism piece 7',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 7 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-55.jpg'],
    piece: 'hyper-realism piece 8',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 8 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-58.jpg'],
    piece: 'hyper-realism piece 11',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 11 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-59.jpg'],
    piece: 'hyper-realism piece 12',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 12 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-60.jpg'],
    piece: 'hyper-realism piece 13',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 13 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-29.jpg'],
    piece: 'hyper-realism piece 15',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 15 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-62.jpg'],
    piece: 'hyper-realism piece 16',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 16 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-63.jpg'],
    piece: 'hyper-realism piece 17',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 17 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-64.jpg'],
    piece: 'hyper-realism piece 18',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 18 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-65.jpg'],
    piece: 'hyper-realism piece 19',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 19 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-67.jpg'],
    piece: 'hyper-realism piece 21',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 21 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-33.jpg'],
    piece: 'hyper-realism piece 22',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 22 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-68.jpg'],
    piece: 'hyper-realism piece 23',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 23 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-34.jpg'],
    piece: 'hyper-realism piece 24',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 24 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-69.jpg'],
    piece: 'hyper-realism piece 25',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 25 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-35.jpg'],
    piece: 'hyper-realism piece 27',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 27 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-70.jpg'],
    piece: 'hyper-realism piece 28',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 28 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-71.jpg'],
    piece: 'hyper-realism piece 30',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 30 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-72.jpg'],
    piece: 'hyper-realism piece 31',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 31 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-73.jpg'],
    piece: 'hyper-realism piece 32',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 32 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-74.jpg'],
    piece: 'hyper-realism piece 33',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 33 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-75.jpg'],
    piece: 'hyper-realism piece 34',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 34 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-76.jpg'],
    piece: 'hyper-realism piece 35',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 35 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-77.jpg'],
    piece: 'hyper-realism piece 36',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 36 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-78.jpg'],
    piece: 'hyper-realism piece 37',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 37 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-38.jpg'],
    piece: 'hyper-realism piece 38',
    category: 'hyper-realism',
    artistName: 'park nichole lladoc',
    alt: 'hyper-realism tattoo piece 38 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-49.jpg'],
    piece: 'realism piece 1',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 1 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-125.jpg'],
    piece: 'realism piece 2',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 2 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-59.jpg'],
    piece: 'realism piece 4',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 4 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-65.jpg'],
    piece: 'realism piece 5',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 5 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-126.jpg'],
    piece: 'realism piece 6',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 6 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-127.jpg'],
    piece: 'realism piece 8',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 8 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-71.jpg'],
    piece: 'realism piece 9',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 9 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-72.jpg'],
    piece: 'realism piece 10',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 10 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-73.jpg'],
    piece: 'realism piece 11',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 11 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-75.jpg'],
    piece: 'realism piece 12',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 12 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-76.jpg'],
    piece: 'realism piece 13',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 13 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-77.jpg'],
    piece: 'realism piece 14',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 14 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-78.jpg'],
    piece: 'realism piece 15',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 15 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-128.jpg'],
    piece: 'realism piece 16',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 16 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-129.jpg'],
    piece: 'realism piece 17',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 17 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-130.jpg'],
    piece: 'realism piece 18',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 18 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-131.jpg'],
    piece: 'realism piece 19',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 19 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-132.jpg'],
    piece: 'realism piece 20',
    category: 'realism',
    artistName: 'park nichole lladoc',
    alt: 'realism tattoo piece 20 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: [
      '/images/portfolio/portfolio-138.jpg',
      '/images/portfolio/portfolio-133.jpg',
      '/images/portfolio/portfolio-134.jpg',
      '/images/portfolio/portfolio-135.jpg',
      '/images/portfolio/portfolio-136.jpg',
      '/images/portfolio/portfolio-137.jpg',
    ],
    piece: 'anime piece 12',
    category: 'anime',
    artistName: 'park nichole lladoc',
    alt: 'anime dragon ball full sleeve tattoo by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-11.jpg'],
    piece: 'anime piece 5',
    category: 'anime',
    artistName: 'park nichole lladoc',
    alt: 'anime tattoo piece 5 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-13.jpg'],
    piece: 'anime piece 7',
    category: 'anime',
    artistName: 'park nichole lladoc',
    alt: 'anime tattoo piece 7 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-14.jpg'],
    piece: 'anime piece 8',
    category: 'anime',
    artistName: 'park nichole lladoc',
    alt: 'anime tattoo piece 8 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-15.jpg'],
    piece: 'anime piece 9',
    category: 'anime',
    artistName: 'park nichole lladoc',
    alt: 'anime tattoo piece 9 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-16.jpg'],
    piece: 'anime piece 10',
    category: 'anime',
    artistName: 'park nichole lladoc',
    alt: 'anime tattoo piece 10 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-17.jpg'],
    piece: 'anime piece 11',
    category: 'anime',
    artistName: 'park nichole lladoc',
    alt: 'anime tattoo piece 11 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-19.jpg'],
    piece: 'blackwork piece 1',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 1 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-20.jpg'],
    piece: 'blackwork piece 2',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 2 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-21.jpg'],
    piece: 'blackwork piece 3',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 3 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-22.jpg'],
    piece: 'blackwork piece 4',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 4 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-23.jpg'],
    piece: 'blackwork piece 5',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 5 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-24.jpg'],
    piece: 'blackwork piece 6',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 6 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-26.jpg'],
    piece: 'blackwork piece 8',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 8 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-27.jpg'],
    piece: 'blackwork piece 9',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 9 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-28.jpg'],
    piece: 'blackwork piece 10',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 10 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-29.jpg'],
    piece: 'blackwork piece 11',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 11 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-30.jpg'],
    piece: 'blackwork piece 12',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 12 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-31.jpg'],
    piece: 'blackwork piece 13',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 13 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-32.jpg'],
    piece: 'blackwork piece 14',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 14 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-33.jpg'],
    piece: 'blackwork piece 15',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 15 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-34.jpg'],
    piece: 'blackwork piece 16',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 16 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-35.jpg'],
    piece: 'blackwork piece 17',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 17 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-36.jpg'],
    piece: 'blackwork piece 18',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 18 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-37.jpg'],
    piece: 'blackwork piece 19',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 19 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-38.jpg'],
    piece: 'blackwork piece 20',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 20 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-39.jpg'],
    piece: 'blackwork piece 21',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 21 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-40.jpg'],
    piece: 'blackwork piece 22',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 22 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-41.jpg'],
    piece: 'blackwork piece 23',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 23 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-42.jpg'],
    piece: 'blackwork piece 24',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 24 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-43.jpg'],
    piece: 'blackwork piece 25',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 25 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-44.jpg'],
    piece: 'blackwork piece 26',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 26 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-45.jpg'],
    piece: 'blackwork piece 27',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 27 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-46.jpg'],
    piece: 'blackwork piece 28',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 28 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-47.jpg'],
    piece: 'blackwork piece 29',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 29 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-48.jpg'],
    piece: 'blackwork piece 30',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork tattoo piece 30 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: [
      '/images/portfolio/portfolio-139.jpg',
      '/images/portfolio/portfolio-140.jpg',
    ],
    piece: 'blackwork piece 31',
    category: 'blackwork',
    artistName: 'park nichole lladoc',
    alt: 'blackwork guardian lion and all-seeing eye full sleeve tattoo by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-79.jpg'],
    piece: 'japanese piece 1',
    category: 'japanese',
    artistName: 'park nichole lladoc',
    alt: 'japanese tattoo piece 1 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-81.jpg'],
    piece: 'japanese piece 3',
    category: 'japanese',
    artistName: 'park nichole lladoc',
    alt: 'japanese tattoo piece 3 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-67.jpg'],
    piece: 'japanese piece 4',
    category: 'japanese',
    artistName: 'park nichole lladoc',
    alt: 'japanese tattoo piece 4 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-82.jpg'],
    piece: 'japanese piece 5',
    category: 'japanese',
    artistName: 'park nichole lladoc',
    alt: 'japanese tattoo piece 5 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-83.jpg'],
    piece: 'japanese piece 6',
    category: 'japanese',
    artistName: 'park nichole lladoc',
    alt: 'japanese tattoo piece 6 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-34.jpg'],
    piece: 'japanese piece 7',
    category: 'japanese',
    artistName: 'park nichole lladoc',
    alt: 'japanese tattoo piece 7 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-84.jpg'],
    piece: 'japanese piece 8',
    category: 'japanese',
    artistName: 'park nichole lladoc',
    alt: 'japanese tattoo piece 8 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-85.jpg'],
    piece: 'japanese piece 9',
    category: 'japanese',
    artistName: 'park nichole lladoc',
    alt: 'japanese tattoo piece 9 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-86.jpg'],
    piece: 'japanese piece 10',
    category: 'japanese',
    artistName: 'park nichole lladoc',
    alt: 'japanese tattoo piece 10 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-87.jpg'],
    piece: 'japanese piece 11',
    category: 'japanese',
    artistName: 'park nichole lladoc',
    alt: 'japanese tattoo piece 11 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-88.jpg'],
    piece: 'japanese piece 12',
    category: 'japanese',
    artistName: 'park nichole lladoc',
    alt: 'japanese tattoo piece 12 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-90.jpg'],
    piece: 'line art piece 1',
    category: 'line art',
    artistName: 'park nichole lladoc',
    alt: 'line art tattoo piece 1 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-91.jpg'],
    piece: 'line art piece 2',
    category: 'line art',
    artistName: 'park nichole lladoc',
    alt: 'line art tattoo piece 2 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-92.jpg'],
    piece: 'line art piece 3',
    category: 'line art',
    artistName: 'park nichole lladoc',
    alt: 'line art tattoo piece 3 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-93.jpg'],
    piece: 'line art piece 4',
    category: 'line art',
    artistName: 'park nichole lladoc',
    alt: 'line art tattoo piece 4 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-94.jpg'],
    piece: 'line art piece 5',
    category: 'line art',
    artistName: 'park nichole lladoc',
    alt: 'line art tattoo piece 5 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-95.jpg'],
    piece: 'line art piece 6',
    category: 'line art',
    artistName: 'park nichole lladoc',
    alt: 'line art tattoo piece 6 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-96.jpg'],
    piece: 'line art piece 7',
    category: 'line art',
    artistName: 'park nichole lladoc',
    alt: 'line art tattoo piece 7 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-80.jpg'],
    piece: 'line art piece 8',
    category: 'line art',
    artistName: 'park nichole lladoc',
    alt: 'line art tattoo piece 8 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-97.jpg'],
    piece: 'line art piece 9',
    category: 'line art',
    artistName: 'park nichole lladoc',
    alt: 'line art tattoo piece 9 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-98.jpg'],
    piece: 'line art piece 10',
    category: 'line art',
    artistName: 'park nichole lladoc',
    alt: 'line art tattoo piece 10 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-99.jpg'],
    piece: 'line art piece 11',
    category: 'line art',
    artistName: 'park nichole lladoc',
    alt: 'line art tattoo piece 11 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-100.jpg'],
    piece: 'line art piece 12',
    category: 'line art',
    artistName: 'park nichole lladoc',
    alt: 'line art tattoo piece 12 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-101.jpg'],
    piece: 'line art piece 13',
    category: 'line art',
    artistName: 'park nichole lladoc',
    alt: 'line art tattoo piece 13 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-102.jpg'],
    piece: 'minimalist piece 1',
    category: 'minimalist',
    artistName: 'park nichole lladoc',
    alt: 'minimalist tattoo piece 1 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-97.jpg'],
    piece: 'minimalist piece 2',
    category: 'minimalist',
    artistName: 'park nichole lladoc',
    alt: 'minimalist tattoo piece 2 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-11.jpg'],
    piece: 'minimalist piece 3',
    category: 'minimalist',
    artistName: 'park nichole lladoc',
    alt: 'minimalist tattoo piece 3 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-103.jpg'],
    piece: 'minimalist piece 4',
    category: 'minimalist',
    artistName: 'park nichole lladoc',
    alt: 'minimalist tattoo piece 4 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-100.jpg'],
    piece: 'minimalist piece 5',
    category: 'minimalist',
    artistName: 'park nichole lladoc',
    alt: 'minimalist tattoo piece 5 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-104.jpg'],
    piece: 'minimalist piece 6',
    category: 'minimalist',
    artistName: 'park nichole lladoc',
    alt: 'minimalist tattoo piece 6 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-105.jpg'],
    piece: 'neo traditional piece 1',
    category: 'neo traditional',
    artistName: 'park nichole lladoc',
    alt: 'neo traditional tattoo piece 1 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-106.jpg'],
    piece: 'neo traditional piece 2',
    category: 'neo traditional',
    artistName: 'park nichole lladoc',
    alt: 'neo traditional tattoo piece 2 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-107.jpg'],
    piece: 'neo traditional piece 3',
    category: 'neo traditional',
    artistName: 'park nichole lladoc',
    alt: 'neo traditional tattoo piece 3 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-110.jpg'],
    piece: 'neo traditional piece 7',
    category: 'neo traditional',
    artistName: 'park nichole lladoc',
    alt: 'neo traditional tattoo piece 7 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-112.jpg'],
    piece: 'polynesian piece 2',
    category: 'polynesian',
    artistName: 'park nichole lladoc',
    alt: 'polynesian tattoo piece 2 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-117.jpg'],
    piece: 'polynesian piece 8',
    category: 'polynesian',
    artistName: 'park nichole lladoc',
    alt: 'polynesian tattoo piece 8 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-41.jpg'],
    piece: 'polynesian piece 9',
    category: 'polynesian',
    artistName: 'park nichole lladoc',
    alt: 'polynesian tattoo piece 9 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: [
      '/images/portfolio/portfolio-141.jpg',
      '/images/portfolio/portfolio-142.jpg',
      '/images/portfolio/portfolio-143.jpg',
    ],
    piece: 'polynesian piece 11',
    category: 'polynesian',
    artistName: 'park nichole lladoc',
    alt: 'polynesian tribal forearm sleeve tattoo by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: [
      '/images/portfolio/portfolio-144.jpg',
      '/images/portfolio/portfolio-145.jpg',
    ],
    piece: 'polynesian piece 12',
    category: 'polynesian',
    artistName: 'park nichole lladoc',
    alt: 'polynesian lotus mandala leg sleeve tattoo by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-120.jpg'],
    piece: 'portrait piece 2',
    category: 'portrait',
    artistName: 'park nichole lladoc',
    alt: 'portrait tattoo piece 2 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-33.jpg'],
    piece: 'portrait piece 3',
    category: 'portrait',
    artistName: 'park nichole lladoc',
    alt: 'portrait tattoo piece 3 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-72.jpg'],
    piece: 'portrait piece 4',
    category: 'portrait',
    artistName: 'park nichole lladoc',
    alt: 'portrait tattoo piece 4 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-40.jpg'],
    piece: 'portrait piece 5',
    category: 'portrait',
    artistName: 'park nichole lladoc',
    alt: 'portrait tattoo piece 5 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-121.jpg'],
    piece: 'portrait piece 6',
    category: 'portrait',
    artistName: 'park nichole lladoc',
    alt: 'portrait tattoo piece 6 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-122.jpg'],
    piece: 'portrait piece 7',
    category: 'portrait',
    artistName: 'park nichole lladoc',
    alt: 'portrait tattoo piece 7 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-123.jpg'],
    piece: 'portrait piece 8',
    category: 'portrait',
    artistName: 'park nichole lladoc',
    alt: 'portrait tattoo piece 8 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-124.jpg'],
    piece: 'portrait piece 9',
    category: 'portrait',
    artistName: 'park nichole lladoc',
    alt: 'portrait tattoo piece 9 by park nichole lladoc — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-146.jpg'],
    piece: 'anime piece 13',
    category: 'anime',
    artistName: 'isaiah recongco',
    alt: 'anime titan transformation calf tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-147.jpg'],
    piece: 'blackwork piece 32',
    category: 'blackwork',
    artistName: 'isaiah recongco',
    alt: 'blackwork skull and mushrooms shoulder tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-148.jpg'],
    piece: 'blackwork piece 33',
    category: 'blackwork',
    artistName: 'isaiah recongco',
    alt: 'blackwork ancient tree face forearm tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-149.jpg'],
    piece: 'blackwork piece 34',
    category: 'blackwork',
    artistName: 'isaiah recongco',
    alt: 'blackwork scorpion and flowers forearm tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-150.jpg'],
    piece: 'blackwork piece 35',
    category: 'blackwork',
    artistName: 'isaiah recongco',
    alt: 'blackwork winged cross chest tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-151.jpg'],
    piece: 'japanese piece 13',
    category: 'japanese',
    artistName: 'isaiah recongco',
    alt: 'japanese hannya mask and katana forearm tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-152.jpg'],
    piece: 'japanese piece 14',
    category: 'japanese',
    artistName: 'isaiah recongco',
    alt: 'japanese maneki-neko lucky cat and matryoshka doll leg tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-153.jpg'],
    piece: 'japanese piece 15',
    category: 'japanese',
    artistName: 'isaiah recongco',
    alt: 'japanese samurai and hannya mask leg sleeve tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-154.jpg'],
    piece: 'japanese piece 16',
    category: 'japanese',
    artistName: 'isaiah recongco',
    alt: 'japanese koi fish and kanji script spine tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-155.jpg'],
    piece: 'japanese piece 17',
    category: 'japanese',
    artistName: 'isaiah recongco',
    alt: 'japanese geisha and dragon leg tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-156.jpg'],
    piece: 'line art piece 14',
    category: 'line art',
    artistName: 'isaiah recongco',
    alt: 'fine line lily flowers spine tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-157.jpg'],
    piece: 'line art piece 15',
    category: 'line art',
    artistName: 'isaiah recongco',
    alt: 'fine line lily flower rib tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-158.jpg'],
    piece: 'line art piece 16',
    category: 'line art',
    artistName: 'isaiah recongco',
    alt: 'fine line lily flower and stars ribcage tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-159.jpg'],
    piece: 'minimalist piece 7',
    category: 'minimalist',
    artistName: 'isaiah recongco',
    alt: 'minimalist butterfly and stars hip tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-160.jpg'],
    piece: 'minimalist piece 8',
    category: 'minimalist',
    artistName: 'isaiah recongco',
    alt: 'minimalist color storm cloud forearm tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-161.jpg'],
    piece: 'minimalist piece 9',
    category: 'minimalist',
    artistName: 'isaiah recongco',
    alt: 'minimalist red ink florals hip tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-162.jpg'],
    piece: 'minimalist piece 10',
    category: 'minimalist',
    artistName: 'isaiah recongco',
    alt: 'minimalist blackwork symbols neck tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-163.jpg'],
    piece: 'minimalist piece 11',
    category: 'minimalist',
    artistName: 'isaiah recongco',
    alt: 'minimalist red ink name script forearm tattoo by isaiah recongco — gorillaz tattoo art studio philippines',
  },
  {
    images: ['/images/portfolio/portfolio-164.jpg'],
    piece: 'minimalist piece 12',
    category: 'minimalist',
    artistName: 'isaiah recongco',
    alt: 'minimalist matching four elements symbol tattoos by isaiah recongco — gorillaz tattoo art studio philippines',
  },
]
